FROM tomcat:7-jre7
MAINTAINER xyz
COPY context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
RUN ["rm", "-fr", "/usr/local/tomcat/webapps/java-sample-app-1.0.0.war"]
COPY java-sample-app-1.0.0.war /usr/local/tomcat/webapps/java-sample-app-1.0.0.war

CMD ["catalina.sh", "run"]
